import type { SupportedLanguage } from './tool-types';

const TOOL_LABELS: Record<SupportedLanguage, Record<string, string>> = {
  en: {
    get_spending_by_merchant: 'merchant spending',
    get_category_totals: 'category totals',
    get_monthly_summary: 'monthly summary',
    get_top_merchants: 'top merchants',
    get_recent_transactions: 'recent transactions',
    search_transactions: 'transactions',
    get_account_overview: 'account overview',
    get_credit_card_snapshot: 'credit card details',
    detect_subscription_price_changes: 'subscription price changes',
    get_financial_health_overview: 'financial health',
    get_cash_flow_projection: 'cash flow projection',
    get_forecast_details: 'forecast details',
    get_financial_overview: 'financial overview',
    get_savings_goals_status: 'savings goals',
    get_recurring_commitments: 'recurring commitments',
    get_upcoming_renewals: 'upcoming renewals',
    get_budget_status: 'budget status',
    compare_spending_periods: 'spending comparison',
    find_spending_anomalies: 'spending anomalies',
    simulate_month_end_scenario: 'month-end scenario',
    create_savings_goal: 'savings goal setup',
    update_savings_goal: 'savings goal update',
    delete_savings_goal: 'savings goal removal',
    create_category: 'new category',
    rename_category: 'category name',
    update_category_budget: 'category budget',
    confirm_recurring_pattern: 'recurring pattern',
    disable_recurring_pattern: 'recurring pattern',
    update_recurring_pattern: 'recurring pattern',
    reassign_transaction_category: 'transaction category',
    edit_transaction: 'transaction details',
    refresh_bank_account: 'bank data',
    set_main_bank_account: 'main account',
  },
  he: {
    get_spending_by_merchant: 'הוצאות לפי בית עסק',
    get_category_totals: 'סיכום קטגוריות',
    get_monthly_summary: 'סיכום חודשי',
    get_top_merchants: 'בתי עסק מובילים',
    get_recent_transactions: 'עסקאות אחרונות',
    search_transactions: 'עסקאות',
    get_account_overview: 'סקירת חשבון',
    get_credit_card_snapshot: 'פרטי כרטיסי אשראי',
    detect_subscription_price_changes: 'שינויי מחיר מנויים',
    get_financial_health_overview: 'בריאות פיננסית',
    get_cash_flow_projection: 'תחזית תזרים',
    get_forecast_details: 'פרטי תחזית',
    get_financial_overview: 'סקירה פיננסית',
    get_savings_goals_status: 'יעדי חיסכון',
    get_recurring_commitments: 'הוצאות קבועות',
    get_upcoming_renewals: 'חידושים קרובים',
    get_budget_status: 'מצב תקציב',
    compare_spending_periods: 'השוואת הוצאות',
    find_spending_anomalies: 'חריגות בהוצאות',
    simulate_month_end_scenario: 'תחזית סוף חודש',
    create_savings_goal: 'הגדרת יעד חיסכון',
    update_savings_goal: 'עדכון יעד חיסכון',
    delete_savings_goal: 'מחיקת יעד חיסכון',
    create_category: 'קטגוריה חדשה',
    rename_category: 'שם קטגוריה',
    update_category_budget: 'תקציב קטגוריה',
    confirm_recurring_pattern: 'תבנית חוזרת',
    disable_recurring_pattern: 'תבנית חוזרת',
    update_recurring_pattern: 'תבנית חוזרת',
    reassign_transaction_category: 'קטגוריית עסקה',
    edit_transaction: 'פרטי עסקה',
    refresh_bank_account: 'נתוני בנק',
    set_main_bank_account: 'חשבון ראשי',
  },
};

export function getToolProgressLabel(language: SupportedLanguage, toolName: string): string {
  return TOOL_LABELS[language][toolName] ?? toolName.replace(/[_-]+/g, ' ').toLowerCase();
}
